---
- hosts: all
  vars:
  - ove_command: reset

  vars_files:
    - ../oah-config.yml


  pre_tasks:
    - include: tasks/init-debian.yml
      when: ansible_os_family == 'Debian'

  roles:
    # Essential roles.
    - oah.oah

    # Conditionally-installed roles.

    # Roles for security and stability on production.

  tasks:
